eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8050/eureka}
okta:
  oauth2:
    issuer: https://dev-79747638.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa9gx4te3GbBSw4A5d7
    client-secret: ZeYpeqFti5TC1CuVa3clrnj-n6gDgh3focz-L90J
    scopes: openid, profile, email, offline_access
